### ISSUE TITLE
Using multiple "Set-Cookie" headers in response doesn't work

### ISSUE THREAD

**Issue by jviding** [NanoHttpd/nanohttpd#317] opened 2016-05-27 04:33 UTC
The response headers are currently stored inside a HashMap object.
The Cookie.unloadQueue method attempts to store all the "Set-Cookie" headers inside the Map but it fails for that every new header overrides the old one because it tries to use the very same "Set-Cookie" key. So only the last one of the "Set-Cookie" headers ever actually makes it into the response.

It's a small bug but rather annoying. Took me a while to figure it out and fix it.

Here's a quick overview of the bugged code:

`    public void unloadQueue(Response response) {
        for (Cookie cookie : this.queue) {
            response.addHeader("Set-Cookie", cookie.getHTTPHeader());
        }
    } /*So we attempt to store multiple "Set-Cookie" values.*/`

This is what we do and fail storing them all:

`public void addHeader(String name, String value) { this.header.put(name, value); }
    /*Each time we try to put ("Set-Cookie",value) we only override the existing one instead of appending the list.*/`

where the header object is:

`private final Map<String, String> header = new HashMap<String, String>()`

And a quote from Java DOC for the put(key,value) method:

> "Associates the specified value with the specified key in this map. If the map previously contained a mapping for the key, the old value is replaced."

**Comment by LordFokas** [comment] 2016-05-27 14:56
Don't mind the labels being switched around... I derped a bit :p 
E see exactly what the problem is but it may take a while for me to get a way to fix that.

Basically when I first implemented cookies back in 2013 (my first commit ever to NanoHTTPD, way before I was a member of the organization) I seem to have overlooked the fact that the header is a map too and replaces previous Set-Cookie headers, effectively only allowing to set one cookie on each request, something that the unit tests overlooked as well by only testing with a single cookie!!

This line is a reminder for me and the team: **THIS ISSUE SHOULD NOT BE CLOSED UNTIL WE NOT ONLY FIX BUT ALSO ADD A MULTIPLE COOKIE TEST CASE TO ENSURE THERE IS NO REGRESSION**

The fix for this will require a whole new header data structure to allow several repeated keys, probably for Set-Cookie only (*pokes* @ritchieGitHub ... *do you have anything against allowing repeated keys for Set-Cookie only?*)

**Comment by ritchieGitHub** [comment] 2016-05-28 06:47
@LordFokas no problem, seems necessary

**Comment by LordFokas** [comment] 2016-09-12 00:27
#374 fixes this and adds regression prevention tests.
@jviding thanks for providing insight on what was wrong.

**Closed by LordFokas** 2016-09-12 00:27 UTC
Labels: bug, ensure-no-regression

**Comment by LordFokas** [comment] 2016-09-12 00:31
@ritchieGitHub I fixed this without touching the header map structure. No special cases, no cheeky workarounds. Instead, cookie headers are stored in a list inside the Response object which writes them directly into the stream, avoiding overlaps. I'm pretty proud of myself for this one :)

**Comment by ritchieGitHub** [comment] 2016-09-12 04:10
nice!

**Comment by mustafaayyildiz** [comment] 2019-12-18 12:48
i'm running web Server using nanohttpd release 2.3.1. but want to use multiple cookie. When does nanohttpd 3.0.0 available?
