### ISSUE TITLE
Cannot set web root as file:///android_asset/ in Android

### ISSUE THREAD

**Issue by darkbasic** [NanoHttpd/nanohttpd#234] opened 2015-10-02 09:48 UTC
Hi,
First of all excuse me if this question is not well suited for a bug tracker, but I don't know of any nanohttpd support channel.
I would like to deploy a web application on Android, stored in the assets directory. Since I use Google APIs I cannot load the html files directly from the filesystem, so I cannot simply do: myWebView.loadUrl("file:///android_asset/index.html");

Instead I embedded nanohttpd in my application and I load it with:
myWebView.loadUrl("http://localhost:8080/");

What's the problem? The problem is that file:///android_asset/ is not an ordinary directory and I don't know any other way to access files inside it.

Ideally I would like to set nanohttpd's web root directory to file:///android_asset/, but I don't know how to do it because it isn't a real path on the filesystem. Any idea?

**Comment by elonen** [comment] 2015-10-02 10:25
​I don't know much about Android, but ​if you can't access the directory
through Java's File class (and other file system facilities), modifying the
SimpleWebServer would probably not be worth the hassle. If android_assets
is the only directory you need to serve files from, I'd suggest subclassing
the NanoHTTPD class directly, and implementing the necessary "file"
operations in a overridden serve() function.

**Comment by darkbasic** [comment] 2015-10-04 12:08
I finally managed to get it working using context.getAssets(), but unfortunately it seems nanohttpd lacks some features needed for Google APIs to work.
I'm not familiar with nanohttpd, do you know what's missing to run something like this[1]?

[1]https://developers.google.com/google-apps/calendar/quickstart/js

**Comment by darkbasic** [comment] 2015-10-07 09:28
I would like to try git to see if it fixes my problem, but I can't get this working:

    @Override
    public Response serve(String uri, Method method,
                          Map<String, String> header,
                          Map<String, String> parameters,
                          Map<String, String> files) {
        String answer = "";
        try {
            BufferedReader reader = null;
            try {
                reader = new BufferedReader(new InputStreamReader(context.getAssets().open("quickstart.html")));
            } catch (IOException e) {
                e.printStackTrace();
            }

            String line = "";
            while ((line = reader.readLine()) != null) {
                answer += line;
            }
            reader.close();

        } catch(IOException ioe) {
            Log.w("Httpd", ioe.toString());
        }


        return new NanoHTTPD.Response(answer);
    }

It seems I can't do "return new NanoHTTPD.Response(answer);" because deprecated. How can I achieve the very same thing (serving quickstart.html from assets) with git version?
Another (even better) solution would be to change the web root path to the assets one.

Thanks

**Comment by vnnv** [comment] 2015-10-08 07:34
You should use:
```return newFixedLengthResponse(answer);```

**Comment by darkbasic** [comment] 2015-10-22 09:57
I managed to get it working on the PC with nanohttpd git, unfortunately nanohttpd git doesn't work on Android!!! In the following screenshot you can see the difference and Chrome's network tab.

![nanohttpd_pc_android](https://cloud.githubusercontent.com/assets/1047358/10662303/e4fdef9c-78b3-11e5-8e75-4751af8d27a8.png)

**Comment by ritchieGitHub** [comment] 2016-01-29 06:21
Anyone able to help with this one?

**Comment by giridharkannan** [comment] 2016-01-29 07:13
Would try to help you out if your could send me your sample code.

**Comment by darkbasic** [comment] 2016-02-01 17:45
@ritchieGitHub it's still not fixed:
#234 To 2.3.0 as not a showstopper for most users, it seems

**Comment by ritchieGitHub** [comment] 2016-02-05 09:03
@darkbasic could you provide a test data for @giridharkannan ?

**Comment by darkbasic** [comment] 2016-02-05 09:45
@ritchieGitHub I already did a few months ago: https://developers.google.com/google-apps/calendar/quickstart/js

**Comment by giridharkannan** [comment] 2016-02-05 10:19
@ritchieGitHub  I don't have any issue in retrieving the calendar info. Am using nanohttpd-webserver:2.2.0. Could you clear the browser cache and check the same.

**Comment by darkbasic** [comment] 2016-02-06 10:10
I just tried once again with 2.2.0-stable: it works if I run nanohttpd on the PC and it doesn work if I run nanohttpd on Android (see previous image posted on 22 Oct 2015). I tested it on a brand new Android Emulator so there is no cache to clean.

**Comment by giridharkannan** [comment] 2016-02-06 10:27
could you give me the screen shot of quickstart.html's response via chrome inspect

**Comment by darkbasic** [comment] 2016-02-06 10:54
It's the same as my previsous screenshot: 
![inspect](https://cloud.githubusercontent.com/assets/1047358/12866249/25a8953e-ccc8-11e5-8cea-c043bdebc352.png)

If you want me to copy paste the exact response from the server just let me know which of the network calls from the screenshot you are interested in.

**Comment by giridharkannan** [comment] 2016-02-06 10:58
Am interested in the response of quickstart.html

**Comment by darkbasic** [comment] 2016-02-06 11:04
This *is* quickstart.html from the Android Emulator, with nanohttpd running on it. Please let me know what do you want exactly because I don't understand.

**Comment by giridharkannan** [comment] 2016-02-06 11:14
Sorry for not being clear.
When you click on localhost in the inspect, it will show you the actual response what the browser has got. I need that screen shot.

**Comment by darkbasic** [comment] 2016-02-06 11:32
I really don't understand, so I made a screencast: https://youtu.be/PIIKpwbDJhc
Hope it helps.

**Comment by giridharkannan** [comment] 2016-02-06 11:56
I need a screen shot similar to this.

![calendar](https://cloud.githubusercontent.com/assets/1427017/12866525/a4a1d642-ccf6-11e5-9e15-d7717d8fd636.png)

**Comment by darkbasic** [comment] 2016-02-06 16:19
Uhm... everything is on the same line, it seems the first inline comment extends for the whole script.
![inspect_response](https://cloud.githubusercontent.com/assets/1047358/12867738/c9fc356e-ccf5-11e5-9539-b08f72182381.png)

**Comment by giridharkannan** [comment] 2016-02-06 17:19
I guess now you could solve the issue by yourself.

**Comment by darkbasic** [comment] 2016-02-06 17:58
Do you *really* mean that *not* using comments is the only solution?
![nanohttpd_quickstart](https://cloud.githubusercontent.com/assets/1047358/12868298/9d20742a-cd03-11e5-9131-2863a9199322.png)

**Comment by LordFokas** [comment] 2016-02-06 18:04
He means that you can fix it.
The solution is not to stop using comments, or to use block comments, because that's just treating the symptom. You need to fix the cause: bad end of line chars.

**Comment by darkbasic** [comment] 2016-02-07 11:40
Ho do you suggest to check what's wrong with my EOL characters? Because they are displayed correctly in both Android Studio and Webstorm IDE, kate and all other editors. Also the very same file works flawlessly with nanohttpd under Linux, it's just Android the problem.

**Comment by giridharkannan** [comment] 2016-02-07 12:21
If you are interested we could take it offline by email and 'll post about our finding if there is some thing to it.

**Comment by darkbasic** [comment] 2016-02-07 14:26
I sent the file to your e-mail address, thanks.

**Comment by darkbasic** [comment] 2016-02-09 16:59
I sent the file to @giridharkannan and the file has no issue. In fact I have the very same problem with a brand new sample file. Also if I run the very same file on linux instead of Android it works flawlessly.
Somehow nanohttpd removes new line characters when running on Android.

**Comment by ritchieGitHub** [comment] 2016-02-14 07:55
@darkbasic  I just had a look at your code example, and noticed that you are indeed deleting the new lines. change the line:
```java
  answer += line;
```
with 
```java
  answer += line+"\n";
```
But I would recomment that you use a stringbuilder for that, but that is off topic here.

**Comment by ritchieGitHub** [comment] 2016-02-19 09:11
@darkbasic what is your status?

**Comment by darkbasic** [comment] 2016-02-19 13:03
The lack of new line characters is gone, thanks. However if I click on the "Authorize" button nothing happens. Any idea?

**Comment by ritchieGitHub** [comment] 2016-02-20 07:38
@darkbasic I have no android development enviorment, so I just see the code sorry. If it is a problem connected to nanohttpd please open a new issue. (It not good to change subject in a issue, that's why I will close this one)

**Closed by ritchieGitHub** 2016-02-20 07:38 UTC
Labels: question
