### ISSUE TITLE
Inputstream from URL

### ISSUE THREAD

**Issue by laminsk** [NanoHttpd/nanohttpd#138] opened 2014-10-03 15:33 UTC
Hi All

I have a quick question regarding playing audio file from remote server through nanohttpd and wondering if you guys can point me in the right direction :)

Using the code below, I could play audio files from sdcard without any problems at all.

 FileInputStream fis = null;
    try {
        fis = new FileInputStream(Environment.getExternalStorageDirectory()
                + "/music/musicfile.mp3");
    } catch (FileNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    return new NanoHTTPD.Response(Status.OK, "audio/mpeg", fis);

I could play the remote audio files (almost flawlessly) using the code below but it's doesn't work as I would have expected. 

url = new URL("http://www.myserver.com/mymusic.mp3");
connection = (HttpURLConnection) url.openConnection();
inputStream = connection.getInputStream();
 return new Response(Response.Status.OK, "application/octet-stream",inputStream);

Problem is, sometimes Media Player will play for a few seconds and stop. It's completely random and when it works, it works fine without a glitch. Perhaps I'm not doing it right as I'm new to Android Dev scene and would be most grateful if any of you guys can help me out with:

1) kindly check and advice what I can do to make this work.
2) storing the file on the device after buffering has finished but I haven't got a clue how to retrieve the file.  

I have tried searching through stackoverflow but not much luck there, and here's hoping someone can actually point me in the right direction!

Many Thanks in Advanced.
Leo

**Comment by ritchieGitHub** [comment] 2015-05-11 16:29
Can we close this issue, or should it be converted in a bug?

**Comment by elonen** [comment] 2015-05-11 16:39
Hi everyone. Since it's unclear whether there's an actual bug involved or now, we'll close this for now. Please reopen though if you can provide more information on when NanoHTTPD seems to fail and, ideally, how to reproduce the problem.

**Closed by elonen** 2015-05-11 16:39 UTC
Labels: question

**Comment by el-mot** [comment] 2015-05-12 05:15
It seems to me chunked-encoding should be used or at least Content-Length must be provided to response.

**Comment by ritchieGitHub** [comment] 2015-05-12 05:20
see #94
