### ISSUE TITLE
Integration with apache.commons.fileupload

### ISSUE THREAD

**Issue by vnnv** [NanoHttpd/nanohttpd#216] opened 2015-07-30 10:53 UTC
I'd like to write an integration with apache.commons.fileupload. 

Currently when a file is uploaded the whole incoming data are saved in a temp file (if the request exceeds 1kb). Next the data  is parsed and new temp files are created for every uploaded file and then you can copy this/thees files to a place you like. On android this can be a limitation if you try to upload bigger files. Imagin you are tring to send 4.4GB movie file. 

Apache fileupload can parse incoming data on the fly and you can get in InputStream to the incoming file and save it on a desired place. 
What do you think guys?

**Comment by ritchieGitHub** [comment] 2015-08-03 05:31
The problem is the amount of code necessary (and runtime memory usage) to reach this goal, in any case it would be a great feature. 

So please yes try to create a pull request to provide this feature! Please keep it all in one class and if you need a new dependency, then do this it in a subclass in a own module, to keep the basic nanohttpd dependency free.

**Comment by vnnv** [comment] 2015-08-03 06:19
I already did it for my project. Current implementation is of 2 classes each less than 50 lines of code. And there is a transient dependency of javax.servlet . I have some more work and some more tests and then I can make pull request.

**Comment by elonen** [comment] 2015-08-09 11:03
Do you have the code online @vnnv ? I'd like to check it out.

**Comment by vnnv** [comment] 2015-08-09 12:12
Not yet, tomorrow I will prepare pull requests for this and for nanolets

**Comment by gkanos** [comment] 2015-09-07 13:45
Does this feature have been integrated into the Nanohttpd? Or is it expected to be integrated at all?

**Comment by ritchieGitHub** [comment] 2015-09-07 14:01
this will be integrated, just not sure yet how ;-) hopefully this weekend

**Comment by ritchieGitHub** [comment] 2015-09-27 04:36
pull request included! thanks!

**Closed by ritchieGitHub** 2015-09-27 04:36 UTC
Labels: enhancement
